version: '3.8'

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=v1.0.0
    container_name: nodejs-compose
    environment:
      - PORT=5000
    ports:
      - "5055:5000"
